name: dbt_nvim
version: '0.1.0'
require-dbt-version: [">=1.3.0", "<2.0.0"]

test-paths: ["tests"]
macro-paths: ["macros"]
log-path: "logs"
target-path: "target"

clean-targets: ["target", "dbt_packages"]

